=== Global19-atlassian-net/smrtflow/docs/SMRT_Link_Service_API/run_design_endpoints/run_design_details_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "pacbio.smrtlink.schemas.rundesign.details",
  "version": "0.1.0",
  "title": "Run Design Details",
  "description": "Complete record of Run Design object",
  "type": "object",
  "properties": {
    "reserved": {
      "title": "Reserved State",
      "description": "Reserved state of this run design",
      "type": "boolean"
    },
    "name": {
      "title": "Run Design Name",
      "description": "Name of this run design",
      "type": "string"
    },
    "runDataModel": {
      "title": "Run Data Model",
      "description": "Serialized XML file specifying metadata of this run design, according to PacBioDataModel.xsd schema",
      "type": "string"
    },
    "id": {
      "title": "Run Design Id",
      "description": "Identifier of this run design",
      "type": "integer"
    },
    "createdAt": {
      "title": "Created at",
      "description": "Time when this run design was created",
      "type": "string",
      "format": "date-time"
    },
    "createdBy": {
      "title": "Created by",
      "description": "Login name of the user who created this run design",
      "type": "string"
    },
    "summary": {
      "title": "Summary",
      "description": "Summary description of this run design",
      "type": "string"
    }
  },
  "required": [
    "reserved",
    "name",
    "runDataModel",
    "id",
    "createdAt",
    "createdBy",
    "summary"
  ],
  "additionalProperties": false
}

=== Global19-atlassian-net/smrtflow/docs/SMRT_Link_Service_API/run_design_endpoints/retrieve_run_design_details_response_sample.json
{
  "reserved": true,
  "name": "Run_20160123_A12_10kEcoli_v2",
  "runDataModel": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<PacBioDataModel xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://pacificbiosciences.com/PacBioDataModel.xsd PacBioDataModel.xsd\" xmlns=\"http://pacificbiosciences.com/PacBioDataModel.xsd\">\r\n  <ExperimentContainer Name=\"NoRS_Standard_Edna.1\" Description=\"${experimentDescription}\" CreatedAt=\"0001-01-01T00:00:00\" ModifiedAt=\"0001-01-01T00:00:00\" ExperimentId=\"315/3150064\">\r\n    <InvestigatorName>Default</InvestigatorName>\r\n    <CreatedDate>0001-01-01</CreatedDate>\r\n    <Runs>\r\n      <Run Name=\"Run_20160123_A12_10kEcoli_v2\" Description=\"ecoliK12_pbi_March2013\" CreatedAt=\"0001-01-01T00:00:00\" ModifiedAt=\"0001-01-01T00:00:00\" UniqueId=\"ed4d2222-aaa1-4630-a79d-1f0aca201b6f\" MetaType=\"Run\" TimeStampedName=\"r54012_20160123_011551\" Status=\"Ready\">\r\n        <Outputs>\r\n          <SubreadSets>\r\n            <SubreadSet Name=\"10kEcoli_2hrImmob_2x-1xBds_A01-Cell1\" UniqueId=\"be60f54e-6d72-4b80-9c5c-2b5876a385c6\" MetaType=\"SubreadSetCollection\" TimeStampedName=\"54012-SubreadSetCollection-2016-15-23T01:15:51.152Z\" xmlns=\"http://pacificbiosciences.com/PacBioDatasets.xsd\">\r\n              <ExternalResources xmlns=\"http://pacificbiosciences.com/PacBioBaseDataModel.xsd\">\r\n                <ExternalResource UniqueId=\"b37a3dd3-d30c-4f83-9e7a-0e9f7fc2c593\" MetaType=\"ExternalResource\" TimeStampedName=\"54012-ExternalResource-2016-15-23T01:15:51.152Z\" />\r\n              </ExternalResources>\r\n              <DataSetMetadata>\r\n                <TotalLength>0</TotalLength>\r\n                <NumRecords>0</NumRecords>\r\n                <Collections xmlns=\"http://pacificbiosciences.com/PacBioCollectionMetadata.xsd\">\r\n                  <CollectionMetadata CreatedAt=\"0001-01-01T00:00:00\" ModifiedAt=\"0001-01-01T00:00:00\" UniqueId=\"a387f481-5d5f-4944-a9b2-67be59bdd6f0\" MetaType=\"CollectionMetadata\" TimeStampedName=\"54012-CollectionMetadata-2016-15-23T01:15:51.152Z\" Status=\"Ready\" InstrumentId=\"54012\" InstrumentName=\"Inst54012\">\r\n                    <InstCtrlVer>String</InstCtrlVer>\r\n                    <SigProcVer>String</SigProcVer>\r\n                    <RunDetails>\r\n                      <TimeStampedName>DefaultTimeStampedRunName</TimeStampedName>\r\n                      <Name>Run_20160123_A12_10kEcoli_v2</Name>\r\n                      <CreatedBy>String</CreatedBy>\r\n                      <WhenCreated>0001-01-01T00:00:00</WhenCreated>\r\n                      <WhenStarted>0001-01-01T00:00:00</WhenStarted>\r\n                    </RunDetails>\r\n                    <WellSample Name=\"10kEcoli_2hrImmob_2x-1xBds_A01\" CreatedAt=\"0001-01-01T00:00:00\" ModifiedAt=\"0001-01-01T00:00:00\">\r\n                      <WellName>A01</WellName>\r\n                      <Concentration>0</Concentration>\r\n                      <InsertSize>10000</InsertSize>\r\n                      <SampleReuseEnabled>false</SampleReuseEnabled>\r\n                      <StageHotstartEnabled>false</StageHotstartEnabled>\r\n                      <SizeSelectionEnabled>true</SizeSelectionEnabled>\r\n                      <UseCount>0</UseCount>\r\n                    </WellSample>\r\n                    <Automation Name=\"Workflow_Magbead.py\">\r\n                      <AutomationParameters xmlns=\"http://pacificbiosciences.com/PacBioBaseDataModel.xsd\">\r\n                        <AutomationParameter Name=\"Exposure\" CreatedAt=\"0001-01-01T00:00:00\" ModifiedAt=\"0001-01-01T00:00:00\" ValueDataType=\"Double\" SimpleValue=\"0.0125\" />\r\n                        <AutomationParameter Name=\"MovieLength\" CreatedAt=\"0001-01-01T00:00:00\" ModifiedAt=\"0001-01-01T00:00:00\" ValueDataType=\"Double\" SimpleValue=\"240\" />\r\n                        <AutomationParameter Name=\"sequencingPixelROI\" CreatedAt=\"0001-01-01T00:00:00\" ModifiedAt=\"0001-01-01T00:00:00\" ValueDataType=\"JSON\" SimpleValue=\"[[0,0,1080,1920]]\" />\r\n                        <AutomationParameter Name=\"traceFilePixelROI\" CreatedAt=\"0001-01-01T00:00:00\" ModifiedAt=\"0001-01-01T00:00:00\" ValueDataType=\"JSON\" SimpleValue=\"[[103,224,64,64],[103,704,64,64],[103,1184,64,64],[103,1664,64,64],[373,224,64,64],[373,704,64,64],[373,1184,64,64],[373,1664,64,64],[643,224,64,64],[643,704,64,64],[643,1184,64,64],[643,1664,64,64],[913,224,64,64],[913,704,64,64],[913,1184,64,64],[913,1664,64,64]]\" />\r\n                        <AutomationParameter Name=\"UseStageHotStart\" CreatedAt=\"0001-01-01T00:00:00\" ModifiedAt=\"0001-01-01T00:00:00\" ValueDataType=\"String\" SimpleValue=\"false\" />\r\n                        <AutomationParameter Name=\"CollectionNumber\" ValueDataType=\"Int32\" SimpleValue=\"0\" />\r\n                        <AutomationParameter Name=\"CellReuseIndex\" ValueDataType=\"Int32\" SimpleValue=\"0\" />\r\n                      </AutomationParameters>\r\n                    </Automation>\r\n                    <CollectionNumber>0</CollectionNumber>\r\n                    <CellIndex>0</CellIndex>\r\n                    <TemplatePrepKit Name=\"SMRTbell™ Template Prep Kit\" Description=\"The SMRTbell™ Template Prep Kit contains reagent supplies to perform SMRTbell library preparations of primer-annealed SMRTbell libraries for insert sizes ranging from 500 bp to over 20 kb.\" Tags=\"Template Prep Kit, TPK\" Version=\"1.0\" PartNumber=\"100-259-100\" Barcode=\"222222100259100100716\" MinInsertSize=\"500\" MaxInsertSize=\"20000\">\r\n                      <LeftAdaptorSequence xmlns=\"http://pacificbiosciences.com/PacBioBaseDataModel.xsd\">ATCTCTCTCAACAACAACAACGGAGGAGGAGGAAAAGAGAGAGAT</LeftAdaptorSequence>\r\n                      <LeftPrimerSequence xmlns=\"http://pacificbiosciences.com/PacBioBaseDataModel.xsd\">aacggaggaggagga</LeftPrimerSequence>\r\n                      <RightAdaptorSequence xmlns=\"http://pacificbiosciences.com/PacBioBaseDataModel.xsd\">ATCTCTCTCAACAACAACAACGGAGGAGGAGGAAAAGAGAGAGAT</RightAdaptorSequence>\r\n                      <RightPrimerSequence xmlns=\"http://pacificbiosciences.com/PacBioBaseDataModel.xsd\">aacggaggaggagga</RightPrimerSequence>\r\n                    </TemplatePrepKit>\r\n                    <BindingKit Name=\"Sequel™ Binding Kit 1.0\" Description=\"The Sequel Binding Kit 1.0 contains reagent supplies to bind prepared DNA template libraries to the Sequel Polymerase 1.0 in preparation for sequencing on the Sequel System. The result is a DNA polymerase/template complex. Sequel Binding Kit 1.0 should be used only with Sequel Sequencing Kit 1.0. Reagent quantities support 24 binding reactions.\" Tags=\"Binding Kit, BDK\" Version=\"1.0\" PartNumber=\"100-619-300\" Barcode=\"222222100619300100716\" />\r\n                    <SequencingKitPlate Name=\"Sequel™ Sequencing Plate 1.0\" Description=\"The DNA Sequencing Kit  contains a sequencing reagent plate with chemistry for single molecule real-time sequencing on the PacBio RS. Reagent quantities support 8 sequencing reactions to be used in conjunction with SMRT® Cell 4Pac(s).  (8 Cells max/Each Row supplies reagents for 1 Sequel SMRT Cell)\" Tags=\"Sequencing Kit, SQK\" Version=\"1.0\" PartNumber=\"100-620-000\" />\r\n                    <Primary>\r\n                      <AutomationName>SequelAlpha</AutomationName>\r\n                      <ConfigFileName>SqlPoC_SubCrf_2C2A-t2.xml</ConfigFileName>\r\n                      <SequencingCondition>DefaultPrimarySequencingCondition</SequencingCondition>\r\n                      <OutputOptions>\r\n                        <ResultsFolder>Analysis_Results</ResultsFolder>\r\n                        <CollectionPathUri>/pbi/collections/315/3150064/r54012_20160123_011551/1_A01/</CollectionPathUri>\r\n                        <CopyFiles>\r\n                          <CollectionFileCopy>Trace</CollectionFileCopy>\r\n                          <CollectionFileCopy>Fasta</CollectionFileCopy>\r\n                          <CollectionFileCopy>Bam</CollectionFileCopy>\r\n                          <CollectionFileCopy>Baz</CollectionFileCopy>\r\n                          <CollectionFileCopy>DarkFrame</CollectionFileCopy>\r\n                        </CopyFiles>\r\n                        <Readout>Pulses</Readout>\r\n                        <MetricsVerbosity>High</MetricsVerbosity>\r\n                      </OutputOptions>\r\n                    </Primary>\r\n                    <Secondary>\r\n                      <AutomationName>DefaultSecondaryAutomationName</AutomationName>\r\n                      <AutomationParameters>\r\n                        <AutomationParameter Name=\"Reference\" CreatedAt=\"0001-01-01T00:00:00\" ModifiedAt=\"0001-01-01T00:00:00\" ValueDataType=\"String\" SimpleValue=\"DefaultSecondaryAnalysisReferenceName\" />\r\n                      </AutomationParameters>\r\n                      <CellCountInJob>0</CellCountInJob>\r\n                    </Secondary>\r\n                    <UserDefinedFields>\r\n                      <DataEntities Name=\" LIMS_IMPORT \" ValueDataType=\"String\" SimpleValue=\"DefaultUserDefinedFieldLIMS\" xmlns=\"http://pacificbiosciences.com/PacBioBaseDataModel.xsd\" />\r\n                    </UserDefinedFields>\r\n                  </CollectionMetadata>\r\n                </Collections>\r\n              </DataSetMetadata>\r\n            </SubreadSet>\r\n            <SubreadSet Name=\"10kEcoli_2hrImmob_2x-1xBds_B01-Cell2\" UniqueId=\"d8622e08-ee6f-4f54-bbab-85fd292887fe\" MetaType=\"SubreadSetCollection\" TimeStampedName=\"54012-SubreadSetCollection-2016-15-23T01:15:51.152Z\" xmlns=\"http://pacificbiosciences.com/PacBioDatasets.xsd\">\r\n              <ExternalResources xmlns=\"http://pacificbiosciences.com/PacBioBaseDataModel.xsd\">\r\n                <ExternalResource UniqueId=\"b8aa492a-70b3-424c-a298-5cbb1e464d8e\" MetaType=\"ExternalResource\" TimeStampedName=\"54012-ExternalResource
