=== Global19-atlassian-net/smrtflow/docs/SMRT_Link_Service_API/run_design_endpoints/run_design_summary_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "pacbio.smrtlink.schemas.rundesign.summary",
	"version": "0.1.0",
	"title": "Run Design Summary",
	"description": "Run Design object in summary form",
	"type" : "object",
	"properties": {
		"reserved": {
			"title": "Reserved State",
			"description": "Reserved state of this run design",
			"type": "boolean"
		},
		"name": {
			"title": "Run Design Name",
			"description": "Name of this run design",
			"type": "string"
		},
		"id": {
			"title": "Run Design Id",
			"description": "Identifier of this run design",
			"type": "integer"
		},
		"createdAt": {
			"title": "Created at",
			"description": "Time when this run design was created",
			"type": "string",
			"format" : "date-time"
		},
		"createdBy": {
			"title": "Created by",
			"description": "Login name of the user who created this run design",
			"type": "string"
		},
		"summary": {
			"title": "Summary",
			"description": "Summary description of this run design",
			"type": "string"
		}
	},
	"required" : [
		"reserved",
		"name",
		"id",
		"createdAt",
		"createdBy",
		"summary"
	],
    "additionalProperties": false
}

=== Global19-atlassian-net/smrtflow/docs/SMRT_Link_Service_API/run_design_endpoints/search_run_designs_response_sample.json
[
  {
    "reserved": true,
    "name": "Run_201511170000_A8",
    "id": 31,
    "createdAt": "2015-11-16T16:02:07.433",
    "createdBy": "root",
    "summary": "lambdaNEB"
  },
  {
    "reserved": true,
    "name": "Run_201511181921_A11",
    "id": 44,
    "createdAt": "2015-11-18T11:46:45.527",
    "createdBy": "root",
    "summary": "lambdaNEB"
  },
  {
    "reserved": true,
    "name": "Run_201511180030_A12",
    "id": 40,
    "createdAt": "2015-11-17T16:30:52.743",
    "createdBy": "root",
    "summary": "lambdaNEB"
  },
  {
    "reserved": true,
    "name": "Run_201511182001_A12",
    "id": 45,
    "createdAt": "2015-11-18T12:01:52.923",
    "createdBy": "root",
    "summary": "lambdaNEB"
  },
  {
    "reserved": true,
    "name": "Run_201511190048_A11",
    "id": 47,
    "createdAt": "2015-11-18T17:35:27.825",
    "createdBy": "root",
    "summary": "lambdaNEB"
  },
  {
    "reserved": true,
    "name": "Run_201511190125_A12",
    "id": 48,
    "createdAt": "2015-11-18T17:38:49.910",
    "createdBy": "root",
    "summary": "lambdaNEB"
  },
  {
    "reserved": true,
    "name": "Run_201511170019_A8",
    "id": 32,
    "createdAt": "2015-11-16T16:20:10.316",
    "createdBy": "root",
    "summary": "lambdaNEB"
  },
  {
    "reserved": true,
    "name": "Run_201511172355_A11",
    "id": 39,
    "createdAt": "2015-11-17T16:03:20.024",
    "createdBy": "root",
    "summary": "lambdaNEB"
  },
  {
    "reserved": true,
    "name": "Run_201511172336_A11",
    "id": 38,
    "createdAt": "2015-11-17T15:37:06.870",
    "createdBy": "root",
    "summary": "lambdaNEB"
  }
]

=== Global19-atlassian-net/smrtflow/docs/SMRT_Link_Service_API/run_design_endpoints/list_all_run_designs_response_sample.json
[{
		"reserved" : true,
		"name" : "Run_201511190522",
		"id" : 51,
		"createdAt" : "2015-11-18T21:22:55.379",
		"createdBy" : "root",
		"summary" : "Dry_Run_111815"
	}, {
		"reserved" : false,
		"name" : "Run_201511141837",
		"id" : 16,
		"createdAt" : "2015-11-14T10:37:45.479",
		"createdBy" : "root",
		"summary" : "run8"
	}, {
		"reserved" : false,
		"name" : "Run_201511141831",
		"id" : 12,
		"createdAt" : "2015-11-14T10:31:48.577",
		"createdBy" : "root",
		"summary" : "run4"
	}, {
		"reserved" : false,
		"name" : "Run_20151119_54016",
		"id" : 57,
		"createdAt" : "2015-11-19T08:02:02.292",
		"createdBy" : "root",
		"summary" : "lambdaNEB"
	}, {
		"reserved" : false,
		"name" : "Run_201511172028",
		"id" : 35,
		"createdAt" : "2015-11-17T12:28:39.236",
		"createdBy" : "root",
		"summary" : "2 cells and inventory for 2 cells"
	}, {
		"reserved" : true,
		"name" : "Run_201511141828_as",
		"id" : 10,
		"createdAt" : "2015-11-14T10:29:42.280",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_20151119",
		"id" : 53,
		"createdAt" : "2015-11-19T05:23:48.702",
		"createdBy" : "root",
		"summary" : "DryRunning"
	}, {
		"reserved" : true,
		"name" : "Run_201511170000_A8",
		"id" : 31,
		"createdAt" : "2015-11-16T16:02:07.433",
		"createdBy" : "root",
		"summary" : "lambdaNEB"
	}, {
		"reserved" : true,
		"name" : "Run_201511162349",
		"id" : 29,
		"createdAt" : "2015-11-16T15:49:27.291",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_201511181921_A11",
		"id" : 44,
		"createdAt" : "2015-11-18T11:46:45.527",
		"createdBy" : "root",
		"summary" : "lambdaNEB"
	}, {
		"reserved" : true,
		"name" : "Run_201511191613",
		"id" : 58,
		"createdAt" : "2015-11-19T08:15:10.834",
		"createdBy" : "root",
		"summary" : "54016_DryRun_111815"
	}, {
		"reserved" : true,
		"name" : "Run_201511140046_as",
		"id" : 6,
		"createdAt" : "2015-11-13T16:46:33.355",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_201511140040_as",
		"id" : 5,
		"createdAt" : "2015-11-13T16:41:02.834",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_201511180034_A7",
		"id" : 41,
		"createdAt" : "2015-11-17T16:37:59.382",
		"createdBy" : "root",
		"summary" : "NoHP_V1_01_circular_89x_l50552"
	}, {
		"reserved" : false,
		"name" : "Run_201511141835",
		"id" : 15,
		"createdAt" : "2015-11-14T10:35:30.642",
		"createdBy" : "root",
		"summary" : "run7"
	}, {
		"reserved" : true,
		"name" : "Run_20151119",
		"id" : 56,
		"createdAt" : "2015-11-19T06:32:23.728",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : false,
		"name" : "Run_201511141841",
		"id" : 20,
		"createdAt" : "2015-11-14T10:42:11.764",
		"createdBy" : "root",
		"summary" : "run12"
	}, {
		"reserved" : true,
		"name" : "Run_201511172026",
		"id" : 34,
		"createdAt" : "2015-11-17T12:26:53.411",
		"createdBy" : "root",
		"summary" : "3 cells but inventory for 2?"
	}, {
		"reserved" : true,
		"name" : "Run_201511180030_A12",
		"id" : 40,
		"createdAt" : "2015-11-17T16:30:52.743",
		"createdBy" : "root",
		"summary" : "lambdaNEB"
	}, {
		"reserved" : false,
		"name" : "Run_201511172004",
		"id" : 33,
		"createdAt" : "2015-11-17T12:04:44.871",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_201511141935",
		"id" : 24,
		"createdAt" : "2015-11-14T11:35:35.215",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : false,
		"name" : "Run_201511141838",
		"id" : 17,
		"createdAt" : "2015-11-14T10:38:34.880",
		"createdBy" : "root",
		"summary" : "run9"
	}, {
		"reserved" : true,
		"name" : "Run_201511141929",
		"id" : 23,
		"createdAt" : "2015-11-14T11:29:39.834",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_201511140007_A8",
		"id" : 2,
		"createdAt" : "2015-11-13T16:07:50.166",
		"createdBy" : "root",
		"summary" : "dryrun"
	}, {
		"reserved" : true,
		"name" : "Run_201511162355",
		"id" : 30,
		"createdAt" : "2015-11-16T15:55:25.854",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : false,
		"name" : "Run_201511141839",
		"id" : 18,
		"createdAt" : "2015-11-14T10:39:54.880",
		"createdBy" : "root",
		"summary" : "run10"
	}, {
		"reserved" : true,
		"name" : "Run_201511140005_A8",
		"id" : 1,
		"createdAt" : "2015-11-13T16:06:29.818",
		"createdBy" : "root",
		"summary" : "dryrun"
	}, {
		"reserved" : true,
		"name" : "Run_201511182001_A12",
		"id" : 45,
		"createdAt" : "2015-11-18T12:01:52.923",
		"createdBy" : "root",
		"summary" : "lambdaNEB"
	}, {
		"reserved" : true,
		"name" : "Run_201511190048_A11",
		"id" : 47,
		"createdAt" : "2015-11-18T17:35:27.825",
		"createdBy" : "root",
		"summary" : "lambdaNEB"
	}, {
		"reserved" : true,
		"name" : "Run_201511190125_A12",
		"id" : 48,
		"createdAt" : "2015-11-18T17:38:49.910",
		"createdBy" : "root",
		"summary" : "lambdaNEB"
	}, {
		"reserved" : true,
		"name" : "Run_201511172236_AS",
		"id" : 36,
		"createdAt" : "2015-11-17T14:37:01.813",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_201511170019_A8",
		"id" : 32,
		"createdAt" : "2015-11-16T16:20:10.316",
		"createdBy" : "root",
		"summary" : "lambdaNEB"
	}, {
		"reserved" : true,
		"name" : "Run_201511190151_as",
		"id" : 49,
		"createdAt" : "2015-11-18T17:51:52.509",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_201511132359",
		"id" : 0,
		"createdAt" : "2015-11-13T15:59:38.898",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : false,
		"name" : "Run_201511141832",
		"id" : 13,
		"createdAt" : "2015-11-14T10:32:49.548",
		"createdBy" : "root",
		"summary" : "run5"
	}, {
		"reserved" : true,
		"name" : "Run_201511141829",
		"id" : 11,
		"createdAt" : "2015-11-14T10:30:41.130",
		"createdBy" : "root",
		"summary" : "run3"
	}, {
		"reserved" : true,
		"name" : "Run_201511172355_A11",
		"id" : 39,
		"createdAt" : "2015-11-17T16:03:20.024",
		"createdBy" : "root",
		"summary" : "lambdaNEB"
	}, {
		"reserved" : false,
		"name" : "Run_201511141833",
		"id" : 14,
		"createdAt" : "2015-11-14T10:34:16.435",
		"createdBy" : "root",
		"summary" : "run6"
	}, {
		"reserved" : true,
		"name" : "Run_201511140040_as",
		"id" : 4,
		"createdAt" : "2015-11-13T16:40:50.888",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_201511141827",
		"id" : 8,
		"createdAt" : "2015-11-14T10:28:30.025",
		"createdBy" : "root",
		"summary" : "run1"
	}, {
		"reserved" : true,
		"name" : "Run_201511190444",
		"id" : 50,
		"createdAt" : "2015-11-18T20:45:02.447",
		"createdBy" : "root",
		"summary" : "54103"
	}, {
		"reserved" : true,
		"name" : "Run_201511141840",
		"id" : 19,
		"createdAt" : "2015-11-14T10:41:22.809",
		"createdBy" : "root",
		"summary" : "run11"
	}, {
		"reserved" : true,
		"name" : "Run_20151119",
		"id" : 54,
		"createdAt" : "2015-11-19T05:35:45.804",
		"createdBy" : "root",
		"summary" : "DryRunning"
	}, {
		"reserved" : true,
		"name" : "Run_201511141828_as",
		"id" : 22,
		"createdAt" : "2015-11-14T10:57:34.913",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_201511172258_as",
		"id" : 37,
		"createdAt" : "2015-11-17T14:58:54.008",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : false,
		"name" : "Run_20151119",
		"id" : 55,
		"createdAt" : "2015-11-19T06:15:32.746",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_201511180113",
		"id" : 43,
		"createdAt" : "2015-11-17T17:14:21.040",
		"createdBy" : "root",
		"summary" : "NoHP_V1_01_circular_89x_l50552"
	}, {
		"reserved" : true,
		"name" : "Run_201511172336_A11",
		"id" : 38,
		"createdAt" : "2015-11-17T15:37:06.870",
		"createdBy" : "root",
		"summary" : "lambdaNEB"
	}, {
		"reserved" : true,
		"name" : "Run_201511142029",
		"id" : 26,
		"createdAt" : "2015-11-14T12:29:48.103",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_201511140010_A11",
		"id" : 3,
		"createdAt" : "2015-11-13T16:10:47.103",
		"createdBy" : "root",
		"summary" : "dryrun"
	}, {
		"reserved" : true,
		"name" : "Run_201511180059",
		"id" : 42,
		"createdAt" : "2015-11-17T17:01:53.734",
		"createdBy" : "root",
		"summary" : "NoHP_V1_01_circular_89x_l50552"
	}, {
		"reserved" : true,
		"name" : "Run_201511142045",
		"id" : 28,
		"createdAt" : "2015-11-14T12:46:18.269",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_201511142037",
		"id" : 27,
		"createdAt" : "2015-11-14T12:37:38.650",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_20151119_54016",
		"id" : 59,
		"createdAt" : "2015-11-19T08:41:22.458",
		"createdBy" : "root",
		"summary" : "Run_20151119_54016"
	}, {
		"reserved" : true,
		"name" : "Run_201511190603",
		"id" : 52,
		"createdAt" : "2015-11-18T22:03:56.932",
		"createdBy" : "root",
		"summary" : "TEST"
	}, {
		"reserved" : true,
		"name" : "Run_201511141828",
		"id" : 9,
		"createdAt" : "2015-11-14T10:29:29.751",
		"createdBy" : "root",
		"summary" : "run2"
	}, {
		"reserved" : true,
		"name" : "Run_201511141843",
		"id" : 21,
		"createdAt" : "2015-11-14T10:44:13.690",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : true,
		"name" : "Run_201511141818_as",
		"id" : 7,
		"createdAt" : "2015-11-14T10:19:15.996",
		"createdBy" : "root",
		"summary" : ""
	}, {
		"reserved" : false,
		"name" : "Run_201511141956",
		"id" : 25,
		"createdAt" : "2015-11-14T11:57:05.588",
		"createdBy" : "root",
		"summary" : "abortRun1"
	}, {
		"reserved" : true,
		"name" : "Run_201511182015",
		"id" : 46,
		"createdAt" : "2015-11-18T12:26:41.229",
		"createdBy" : "root",
		"summary" : "54013_1Cell_2Hr_11182015_ReleaseReagents"
	}
]
