=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/post/create_any_job_response_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "pacbio.secondary.schemas.job.object",
  "version": "0.1.0",
  "title": "Job Object",
  "description": "Job object schema",
  "type": "object",
  "properties": {
    "name": {
      "title": "Job Name",
      "description": "Name of this job",
      "type": "string"
    },
    "jobTypeId": {
      "title": "Job Type Id",
      "description": "Type identifier of this job",
      "type": "string"
    },
    "id": {
      "title": "Job Id",
      "description": "Identifier of this job",
      "type": "integer"
    },
    "uuid": {
      "title": "UUID",
      "description": "UUID of this job",
      "type": "string",
      "format": "uuid",
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    },
    "createdAt": {
      "title": "Created at",
      "description": "Time when this job was created",
      "type": "string",
      "format": "date-time"
    },
    "updatedAt": {
      "title": "Updated at",
      "description": "Time when this job was updated",
      "type": "string",
      "format": "date-time"
    },
    "path": {
      "title": "Job path",
      "description": "Path to the job folder",
      "type": "string",
      "format": "uri"
    },
    "state": {
      "title": "Job State",
      "description": "Current job state, one of CREATED, SUBMITTED, RUNNING, SUCCESSFUL, FAILED, KILLED, STOPPED states",
      "type": "string"
    },
    "comment": {
      "title": "Comment",
      "description": "Comment describing this job",
      "type": "string"
    },
    "jsonSettings": {
      "title": "JSON Settings",
      "description": "Serialized JSON file that contains settings for this job",
      "type": "string"
    }
  },
  "required": [
    "name",
    "jobTypeId",
    "id",
    "uuid",
    "createdAt",
    "updatedAt",
    "path",
    "state",
    "comment",
    "jsonSettings"
  ],
  "additionalProperties": false
}

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/list_jobs_import-dataset.json
[
  {
    "name": "Job import-dataset",
    "updatedAt": "2015-11-13T11:50:17.801-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000002",
    "state": "SUCCESSFUL",
    "uuid": "72804c90-1868-481a-9b55-4b734e858a17",
    "jobTypeId": "import-dataset",
    "id": 2,
    "comment": "Importing DataSet ImportDataSetOptions(/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/current/bundles/smrtinub/current/private/pacbio/canneddata/lambdaTINY/m150404_101626_42267_c100807920800000001823174110291514_s1_p0.subreadset.xml,PacBio.DataSet.SubreadSet)",
    "createdAt": "2015-11-13T11:50:17.801-08:00",
    "jsonSettings": "{\"path\":\"/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/current/bundles/smrtinub/current/private/pacbio/canneddata/lambdaTINY/m150404_101626_42267_c100807920800000001823174110291514_s1_p0.subreadset.xml\",\"datasetType\":\"PacBio.DataSet.SubreadSet\"}"
  },
  {
    "name": "Job import-dataset",
    "updatedAt": "2015-11-13T11:57:44.743-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000005",
    "state": "SUCCESSFUL",
    "uuid": "6831fc97-38f3-4122-9472-045fbc9c2536",
    "jobTypeId": "import-dataset",
    "id": 5,
    "comment": "Importing DataSet ImportDataSetOptions(/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/current/bundles/smrtinub/current/private/pacbio/canneddata/lambdaTINY/m150404_101626_42267_c100807920800000001823174110291514_s1_p0.subreadset.xml,PacBio.DataSet.SubreadSet)",
    "createdAt": "2015-11-13T11:57:44.743-08:00",
    "jsonSettings": "{\"path\":\"/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/current/bundles/smrtinub/current/private/pacbio/canneddata/lambdaTINY/m150404_101626_42267_c100807920800000001823174110291514_s1_p0.subreadset.xml\",\"datasetType\":\"PacBio.DataSet.SubreadSet\"}"
  },
  {
    "name": "Job import-dataset",
    "updatedAt": "2015-11-16T12:05:46.156-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000009",
    "state": "SUCCESSFUL",
    "uuid": "2f5fc160-0264-4bdf-8445-47a4fb8259ef",
    "jobTypeId": "import-dataset",
    "id": 9,
    "comment": "Importing DataSet ImportDataSetOptions(/pbi/collections/313/3130022/r54004_20151116_190652/1_A01/m54004_151116_190700.subreadset.xml,PacBio.DataSet.SubreadSet)",
    "createdAt": "2015-11-16T12:05:46.156-08:00",
    "jsonSettings": "{\"path\":\"/pbi/collections/313/3130022/r54004_20151116_190652/1_A01/m54004_151116_190700.subreadset.xml\",\"datasetType\":\"PacBio.DataSet.SubreadSet\"}"
  },
  {
    "name": "Job import-dataset",
    "updatedAt": "2015-11-16T14:21:48.359-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000012",
    "state": "SUCCESSFUL",
    "uuid": "50f8b1d7-c1f7-42f6-accd-93611de7bd7f",
    "jobTypeId": "import-dataset",
    "id": 12,
    "comment": "Importing DataSet ImportDataSetOptions(/pbi/collections/313/3130022/r54004_20151116_214425/1_A01/m54004_151116_214433.subreadset.xml,PacBio.DataSet.SubreadSet)",
    "createdAt": "2015-11-16T14:21:48.359-08:00",
    "jsonSettings": "{\"path\":\"/pbi/collections/313/3130022/r54004_20151116_214425/1_A01/m54004_151116_214433.subreadset.xml\",\"datasetType\":\"PacBio.DataSet.SubreadSet\"}"
  },
  {
    "name": "Job import-dataset",
    "updatedAt": "2015-11-16T18:57:38.991-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000014",
    "state": "SUCCESSFUL",
    "uuid": "0c7fe101-8b49-45e6-bc83-0852b10fabef",
    "jobTypeId": "import-dataset",
    "id": 14,
    "comment": "Importing DataSet ImportDataSetOptions(/pbi/collections/313/3130023/r54012_20151116_234924/1_A01/m54012_151116_235506.subreadset.xml,PacBio.DataSet.SubreadSet)",
    "createdAt": "2015-11-16T18:57:38.991-08:00",
    "jsonSettings": "{\"path\":\"/pbi/collections/313/3130023/r54012_20151116_234924/1_A01/m54012_151116_235506.subreadset.xml\",\"datasetType\":\"PacBio.DataSet.SubreadSet\"}"
  },
  {
    "name": "Job import-dataset",
    "updatedAt": "2015-11-16T19:13:52.152-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000015",
    "state": "SUCCESSFUL",
    "uuid": "a5df53e8-c286-43a5-93bf-671137271f43",
    "jobTypeId": "import-dataset",
    "id": 15,
    "comment": "Importing DataSet ImportDataSetOptions(/pbi/collections/313/3130023/r54011_20151116_235523/1_A01/m54011_151117_000014.subreadset.xml,PacBio.DataSet.SubreadSet)",
    "createdAt": "2015-11-16T19:13:52.152-08:00",
    "jsonSettings": "{\"path\":\"/pbi/collections/313/3130023/r54011_20151116_235523/1_A01/m54011_151117_000014.subreadset.xml\",\"datasetType\":\"PacBio.DataSet.SubreadSet\"}"
  },
  {
    "name": "Job import-dataset",
    "updatedAt": "2015-11-16T20:30:50.396-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000016",
    "state": "SUCCESSFUL",
    "uuid": "00057a50-5b6d-476e-8b6a-fa7a19382cbc",
    "jobTypeId": "import-dataset",
    "id": 16,
    "comment": "Importing DataSet ImportDataSetOptions(/pbi/collections/313/3130024/r54008_20151117_002008/2_B01/m54008_151117_011028.subreadset.xml,PacBio.DataSet.SubreadSet)",
    "createdAt": "2015-11-16T20:30:50.396-08:00",
    "jsonSettings": "{\"path\":\"/pbi/collections/313/3130024/r54008_20151117_002008/2_B01/m54008_151117_011028.subreadset.xml\",\"datasetType\":\"PacBio.DataSet.SubreadSet\"}"
  },
  {
    "name": "Job import-dataset",
    "updatedAt": "2015-11-16T21:42:04.686-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000017",
    "state": "SUCCESSFUL",
    "uuid": "14bac755-2357-4ade-b26a-eb6af41e7c77",
    "jobTypeId": "import-dataset",
    "id": 17,
    "comment": "Importing DataSet ImportDataSetOptions(/pbi/collections/313/3130023/r54012_20151116_234924/2_B01/m54012_151117_023631.subreadset.xml,PacBio.DataSet.SubreadSet)",
    "createdAt": "2015-11-16T21:42:04.686-08:00",
    "jsonSettings": "{\"path\":\"/pbi/collections/313/3130023/r54012_20151116_234924/2_B01/m54012_151117_023631.subreadset.xml\",\"datasetType\":\"PacBio.DataSet.SubreadSet\"}"
  },
  {
    "name": "Job import-dataset",
    "updatedAt": "2015-11-16T21:55:31.586-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000018",
    "state": "SUCCESSFUL",
    "uuid": "9ffacda6-4d8c-405f-a3d8-2fbe16f13014",
    "jobTypeId": "import-dataset",
    "id": 18,
    "comment": "Importing DataSet ImportDataSetOptions(/pbi/collections/313/3130023/r54011_20151116_235523/2_B01/m54011_151117_024041.subreadset.xml,PacBio.DataSet.SubreadSet)",
    "createdAt": "2015-11-16T21:55:31.586-08:00",
    "jsonSettings": "{\"path\":\"/pbi/collections/313/3130023/r54011_20151116_235523/2_B01/m54011_151117_024041.subreadset.xml\",\"datasetType\":\"PacBio.DataSet.SubreadSet\"}"
  },
  {
    "name": "Job import-dataset",
    "updatedAt": "2015-11-17T00:26:51.391-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000019",
    "state": "SUCCESSFUL",
    "uuid": "65fa2786-3b7d-46d5-a34b-bc47ea56d56d",
    "jobTypeId": "import-dataset",
    "id": 19,
    "comment": "Importing DataSet ImportDataSetOptions(/pbi/collections/313/3130023/r54012_20151116_234924/3_C01/m54012_151117_052037.subreadset.xml,PacBio.DataSet.SubreadSet)",
    "createdAt": "2015-11-17T00:26:51.391-08:00",
    "jsonSettings": "{\"path\":\"/pbi/collections/313/3130023/r54012_20151116_234924/3_C01/m54012_151117_052037.subreadset.xml\",\"datasetType\":\"PacBio.DataSet.SubreadSet\"}"
  }
]

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/get_jobs_pbsmrtpipe_38.json
{
  "name": "A4_All4mer_1hr_launchChem",
  "updatedAt": "2015-11-18T12:24:35.413-08:00",
  "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000038",
  "state": "SUCCESSFUL",
  "uuid": "ea3c0962-f37b-43b6-82b3-051d41dc82c0",
  "jobTypeId": "pbsmrtpipe",
  "id": 38,
  "comment": "pbsmrtpipe pbsmrtpipe.pipelines.sa3_ds_resequencing PbSmrtPipeJobOptions(pbsmrtpipe.pipelines.sa3_ds_resequencing,List(BoundEntryPoint(eid_subread,/pbi/collections/313/3130022/r54004_20151117_231855/1_A01/m54004_151117_231902.subreadset.xml), BoundEntryPoint(eid_ref_dataset,/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000008/pacbio-reference/All4mer_V2_44_circular_72x_l50256/referenceset.xml)),List(PipelineStrOption(genomic_consensus.task_options.algorithm,Name genomic_consensus.task_options.algorithm,quiver,Description genomic_consensus.task_options.algorithm), PipelineStrOption(genomic_consensus.task_options.diploid,Name genomic_consensus.task_options.diploid,false,Description genomic_consensus.task_options.diploid), PipelineStrOption(genomic_consensus.task_options.min_confidence,Name genomic_consensus.task_options.min_confidence,40,Description genomic_consensus.task_options.min_confidence), PipelineStrOption(genomic_consensus.task_options.min_coverage,Name genomic_consensus.task_options.min_coverage,5,Description genomic_consensus.task_options.min_coverage), PipelineStrOption(pbalign.task_options.algorithm_options,Name pbalign.task_options.algorithm_options,-minMatch 12 -bestn 10 -minPctIdentity 70.0,Description pbalign.task_options.algorithm_options), PipelineStrOption(pbalign.task_options.concordant,Name pbalign.task_options.concordant,true,Description pbalign.task_options.concordant), PipelineStrOption(pbalign.task_options.consolidate_aligned_bam,Name pbalign.task_options.consolidate_aligned_bam,false,Description pbalign.task_options.consolidate_aligned_bam), PipelineStrOption(pbalign.task_options.consolidate_n_files,Name pbalign.task_options.consolidate_n_files,1,Description pbalign.task_options.consolidate_n_files), PipelineStrOption(pbalign.task_options.hit_policy,Name pbalign.task_options.hit_policy,randombest,Description pbalign.task_options.hit_policy), PipelineStrOption(pbalign.task_options.min_accuracy,Name pbalign.task_options.min_accuracy,70.0,Description pbalign.task_options.min_accuracy), PipelineStrOption(pbalign.task_options.min_length,Name pbalign.task_options.min_length,50,Description pbalign.task_options.min_length)),List(PipelineBooleanOption(pbsmrtpipe.options.debug_mode,pbsmrtpipe DEBUG Mode,false,Enable pbsmrtpipe DEBUG Mode to pbsmrtpipe.log and master.log), PipelineIntOption(pbsmrtpipe.options.max_nproc,Max Number of Processors per Task,24,Max Number of Processors), PipelineStrOption(pbsmrtpipe.options.tmp_dir,Tmp directory,/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/tmp_dir,Root location to temp directory), PipelineBooleanOption(pbsmrtpipe.options.chunk_mode,Enable chunk mode,true,Enable chunk mode to create chunk.json from registered chunkable tasks), PipelineIntOption(pbsmrtpipe.options.max_total_nproc,Max Total Number of processors to use per pipeline execution,1000,Total Max Number of slots/proc to use), PipelineIntOption(pbsmrtpipe.options.max_nchunks,Max Number of Chunks per Task,24,Max Number of Chunks per task), PipelineBooleanOption(pbsmrtpipe.options.distributed_mode,Enable Distributed mode,true,Enable Distributed mode to submit jobs to the cluster resources. CLUSTER_MANAGER_TMPL_DIR must be set), PipelineBooleanOption(pbsmrtpipe.options.exit_on_failure,Enable Exit on Failure,false,Exit on the first failed task.), PipelineStrOption(pbsmrtpipe.options.cluster_manager,Cluster Template Directory,/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/generated/config/jms_templates,Directory of Cluster templates (must contain start.tmpl and stop.tmpl) or python module path (e.g, pbsmrtpipe.my_module.sge), PipelineIntOption(pbsmrtpipe.options.max_nworkers,Max Number of Workers,100,Max Number of concurrently running tasks. (Note:  max_nproc will restrict the number of workers if max_nworkers * max_nproc > max_total_nproc))),,Some(http://smrtlink-beta.nanofluidics.com:8081/secondary-analysis/job-manager/jobs/pbsmrtpipe/ea3c0962-f37b-43b6-82b3-051d41dc82c0),None)",
  "createdAt": "2015-11-18T12:24:35.413-08:00",
  "jsonSettings": "{\"name\":\"A4_All4mer_1hr_launchChem\",\"entryPoints\":[{\"entryId\":\"eid_subread\",\"fileTypeId\":\"PacBio.DataSet.SubreadSet\",\"datasetId\":38},{\"entryId\":\"eid_ref_dataset\",\"fileTypeId\":\"PacBio.DataSet.ReferenceSet\",\"datasetId\":12}],\"workflowOptions\":[],\"taskOptions\":[{\"optionId\":\"genomic_consensus.task_options.algorithm\",\"value\":\"quiver\",\"optionTypeId\":\"pbsmrtpipe.option_types.string\"},{\"optionId\":\"genomic_consensus.task_options.diploid\",\"value\":false,\"optionTypeId\":\"pbsmrtpipe.option_types.boolean\"},{\"optionId\":\"genomic_consensus.task_options.min_confidence\",\"value\":40,\"optionTypeId\":\"pbsmrtpipe.option_types.integer\"},{\"optionId\":\"genomic_consensus.task_options.min_coverage\",\"value\":5,\"optionTypeId\":\"pbsmrtpipe.option_types.integer\"},{\"optionId\":\"pbalign.task_options.algorithm_options\",\"value\":\"-minMatch 12 -bestn 10 -minPctIdentity 70.0\",\"optionTypeId\":\"pbsmrtpipe.option_types.string\"},{\"optionId\":\"pbalign.task_options.concordant\",\"value\":true,\"optionTypeId\":\"pbsmrtpipe.option_types.boolean\"},{\"optionId\":\"pbalign.task_options.consolidate_aligned_bam\",\"value\":false,\"optionTypeId\":\"pbsmrtpipe.option_types.boolean\"},{\"optionId\":\"pbalign.task_options.consolidate_n_files\",\"value\":1,\"optionTypeId\":\"pbsmrtpipe.option_types.integer\"},{\"optionId\":\"pbalign.task_options.hit_policy\",\"value\":\"randombest\",\"optionTypeId\":\"pbsmrtpipe.option_types.string\"},{\"optionId\":\"pbalign.task_options.min_accuracy\",\"value\":70.0,\"optionTypeId\":\"pbsmrtpipe.option_types.float\"},{\"optionId\":\"pbalign.task_options.min_length\",\"value\":50,\"optionTypeId\":\"pbsmrtpipe.option_types.integer\"}],\"pipelineId\":\"pbsmrtpipe.pipelines.sa3_ds_resequencing\"}"
}

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/post/create_convert-rs-movie_job_response_sample.json
{
  "name": "Job convert-rs-movie",
  "updatedAt": "2016-02-23T12:16:21.391-08:00",
  "path": "",
  "state": "CREATED",
  "uuid": "92804077-bd0f-41ef-913f-0d7da0ef5656",
  "jobTypeId": "convert-rs-movie",
  "id": 136,
  "comment": "RS movie convert to HdfSubread XML MovieMetadataToHdfSubreadOptions(/pbi/collections/315/3150104/r54007_20160221_004312/1_A01/m54007_160221_004320.metadata.xml,movie-run-metadata)",
  "createdAt": "2016-02-23T12:16:21.391-08:00",
  "jsonSettings": "{\"path\":\"/pbi/collections/315/3150104/r54007_20160221_004312/1_A01/m54007_160221_004320.metadata.xml\",\"name\":\"movie-run-metadata\"}"
}

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/post/create_merge-datasets_job_response_sample.json
{
	"name" : "Job merge-datasets",
	"updatedAt" : "2016-02-23T09:41:34.741-08:00",
	"path" : "",
	"state" : "CREATED",
	"uuid" : "b8fb1138-4a00-4baf-a754-fc37492d5f00",
	"jobTypeId" : "merge-datasets",
	"id" : 131,
	"comment" : "Merging Datasets MergeDataSetOptions(PacBio.DataSet.SubreadSet,List(/pbi/dept/secondary/siv/testdata/SA3-DS/lambda/2372215/0007_tiny/Analysis_Results/m150404_101626_42267_c100807920800000001823174110291514_s1_p0.all.subreadset.xml, /mnt/appslab/projects/2015/starfish_hlac/ccs2/histo_DPB1_96pool_10fmol_reheader.subreadset.xml),mergedSubreadDataset)",
	"createdAt" : "2016-02-23T09:41:34.741-08:00",
	"jsonSettings" : "{\"datasetType\":\"PacBio.DataSet.SubreadSet\",\"paths\":[\"/pbi/dept/secondary/siv/testdata/SA3-DS/lambda/2372215/0007_tiny/Analysis_Results/m150404_101626_42267_c100807920800000001823174110291514_s1_p0.all.subreadset.xml\",\"/mnt/appslab/projects/2015/starfish_hlac/ccs2/histo_DPB1_96pool_10fmol_reheader.subreadset.xml\"],\"name\":\"mergedSubreadDataset\"}"
}

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/get_jobs_merge-datasets_252.json
{
	"name" : "Job merge-datasets",
	"updatedAt" : "2015-11-30T15:06:10.415-08:00",
	"path" : "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000252",
	"state" : "SUCCESSFUL",
	"uuid" : "1576c753-478c-46c6-ad44-9936665df1b7",
	"jobTypeId" : "merge-datasets",
	"id" : 252,
	"comment" : "Merging Datasets MergeDataSetOptions(PacBio.DataSet.SubreadSet,List(/pbi/collections/315/3150014/r54007_20151127_210248/1_A01/m54007_151127_210535.subreadset.xml, /pbi/collections/315/3150014/r54007_20151127_210248/2_B01/m54007_151128_021155.subreadset.xml, /pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000251/merged.dataset.xml),Auto-merged subreads @ 1448924770520)",
	"createdAt" : "2015-11-30T15:06:10.415-08:00",
	"jsonSettings" : "{\"datasetType\":\"PacBio.DataSet.SubreadSet\",\"paths\":[\"/pbi/collections/315/3150014/r54007_20151127_210248/1_A01/m54007_151127_210535.subreadset.xml\",\"/pbi/collections/315/3150014/r54007_20151127_210248/2_B01/m54007_151128_021155.subreadset.xml\",\"/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000251/merged.dataset.xml\"],\"name\":\"Auto-merged subreads @ 1448924770520\"}"
}

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/post/create_import-datastore_job_response_sample.json
{
  "name": "Job import-datastore",
  "updatedAt": "2016-02-23T13:20:46.953-08:00",
  "path": "",
  "state": "CREATED",
  "uuid": "2975ddb9-9cde-4543-bda1-beed3b20d0da",
  "jobTypeId": "import-datastore",
  "id": 137,
  "comment": "Importing DataStore ImportDataStoreOptions(/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000017/datastore.json)",
  "createdAt": "2016-02-23T13:20:46.953-08:00",
  "jsonSettings": "{\"path\":\"/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000017/datastore.json\"}"
}

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/list_jobs_convert-fasta-reference.json
[
  {
    "name": "Job convert-fasta-reference",
    "updatedAt": "2015-11-13T11:50:07.389-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000001",
    "state": "SUCCESSFUL",
    "uuid": "535b9671-4f2d-435a-a4d6-34333dac39d0",
    "jobTypeId": "convert-fasta-reference",
    "id": 1,
    "comment": "Import/Convert Fasta File to DataSet ConvertImportFastaOptions(/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/install/smrtsuite-fromsrc_3.0.0.166987/admin/bin/../../../../current/bundles/smrtinub/current/private/pacbio/canneddata/lambdaNEB.fasta,lambdaNEB,haploid,lambda_phage)",
    "createdAt": "2015-11-13T11:50:07.389-08:00",
    "jsonSettings": "{\"path\":\"/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/install/smrtsuite-fromsrc_3.0.0.166987/admin/bin/../../../../current/bundles/smrtinub/current/private/pacbio/canneddata/lambdaNEB.fasta\",\"name\":\"lambdaNEB\",\"ploidy\":\"haploid\",\"organism\":\"lambda_phage\"}"
  },
  {
    "name": "Job convert-fasta-reference",
    "updatedAt": "2015-11-13T11:57:37.473-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000004",
    "state": "SUCCESSFUL",
    "uuid": "d0a65373-ac76-44c6-afbe-614bc15c6d0e",
    "jobTypeId": "convert-fasta-reference",
    "id": 4,
    "comment": "Import/Convert Fasta File to DataSet ConvertImportFastaOptions(/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/install/smrtsuite-fromsrc_3.0.0.166987/admin/bin/../../../../current/bundles/smrtinub/current/private/pacbio/canneddata/lambdaNEB.fasta,lambdaNEB,haploid,lambda_phage)",
    "createdAt": "2015-11-13T11:57:37.473-08:00",
    "jsonSettings": "{\"path\":\"/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/install/smrtsuite-fromsrc_3.0.0.166987/admin/bin/../../../../current/bundles/smrtinub/current/private/pacbio/canneddata/lambdaNEB.fasta\",\"name\":\"lambdaNEB\",\"ploidy\":\"haploid\",\"organism\":\"lambda_phage\"}"
  },
  {
    "name": "Job convert-fasta-reference",
    "updatedAt": "2015-11-16T11:16:47.758-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000008",
    "state": "SUCCESSFUL",
    "uuid": "a82f550b-0ad2-4d5b-97bc-bfe3a0698905",
    "jobTypeId": "convert-fasta-reference",
    "id": 8,
    "comment": "Import/Convert Fasta File to DataSet ConvertImportFastaOptions(/mnt/secondary/iSmrtanalysis/current/common/references/All4mer_V2_44_circular_72x_l50256/sequence/All4mer_V2_44_circular_72x_l50256.fasta,All4mer_V2_44_circular_72x_l50256,haploid,NA)",
    "createdAt": "2015-11-16T11:16:47.758-08:00",
    "jsonSettings": "{\"path\":\"/mnt/secondary/iSmrtanalysis/current/common/references/All4mer_V2_44_circular_72x_l50256/sequence/All4mer_V2_44_circular_72x_l50256.fasta\",\"name\":\"All4mer_V2_44_circular_72x_l50256\",\"ploidy\":\"haploid\",\"organism\":\"NA\"}"
  },
  {
    "name": "Job convert-fasta-reference",
    "updatedAt": "2015-11-16T13:15:59.267-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000011",
    "state": "SUCCESSFUL",
    "uuid": "d8cb3d9e-e6ee-48c9-9631-1ac29c01fd36",
    "jobTypeId": "convert-fasta-reference",
    "id": 11,
    "comment": "Import/Convert Fasta File to DataSet ConvertImportFastaOptions(/mnt/secondary/iSmrtanalysis/current/common/references/tkb_C5_circular_23x_l92782/sequence/tkb_C5_circular_23x_l92782.fasta,tkb_C5_circular_23x_l92782,haploid,NA)",
    "createdAt": "2015-11-16T13:15:59.267-08:00",
    "jsonSettings": "{\"path\":\"/mnt/secondary/iSmrtanalysis/current/common/references/tkb_C5_circular_23x_l92782/sequence/tkb_C5_circular_23x_l92782.fasta\",\"name\":\"tkb_C5_circular_23x_l92782\",\"ploidy\":\"haploid\",\"organism\":\"NA\"}"
  },
  {
    "name": "Job convert-fasta-reference",
    "updatedAt": "2015-11-20T09:58:41.035-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000092",
    "state": "FAILED",
    "uuid": "65e2f87f-d361-400d-88e3-42609035bc8f",
    "jobTypeId": "convert-fasta-reference",
    "id": 92,
    "comment": "Import/Convert Fasta File to DataSet ConvertImportFastaOptions(/lustre/hpcprod/mhsieh/quiver/hummingbird/reference/sequence/reference.fasta,hummingbird_falcon,haploid,bird)",
    "createdAt": "2015-11-20T09:58:41.035-08:00",
    "jsonSettings": "{\"path\":\"/lustre/hpcprod/mhsieh/quiver/hummingbird/reference/sequence/reference.fasta\",\"name\":\"hummingbird_falcon\",\"ploidy\":\"haploid\",\"organism\":\"bird\"}"
  },
  {
    "name": "Job convert-fasta-reference",
    "updatedAt": "2015-11-23T10:16:52.771-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000131",
    "state": "SUCCESSFUL",
    "uuid": "50835c35-4f41-44d6-b2fc-7950caf4c5f5",
    "jobTypeId": "convert-fasta-reference",
    "id": 131,
    "comment": "Import/Convert Fasta File to DataSet ConvertImportFastaOptions(/pbi/analysis/smrtportal/internal/userdata/references/pBR322_plasmidbell_4361bp_circular_6x_l52872/sequence/pBR322_plasmidbell_4361bp_circular_6x_l52872.fasta,pBR322_plasmidbell_4361bp_circular_6x_l52872,haploid,NA)",
    "createdAt": "2015-11-23T10:16:52.771-08:00",
    "jsonSettings": "{\"path\":\"/pbi/analysis/smrtportal/internal/userdata/references/pBR322_plasmidbell_4361bp_circular_6x_l52872/sequence/pBR322_plasmidbell_4361bp_circular_6x_l52872.fasta\",\"name\":\"pBR322_plasmidbell_4361bp_circular_6x_l52872\",\"ploidy\":\"haploid\",\"organism\":\"NA\"}"
  },
  {
    "name": "Job convert-fasta-reference",
    "updatedAt": "2015-11-23T13:20:02.706-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000139",
    "state": "SUCCESSFUL",
    "uuid": "82c73b2a-9a8c-4fcd-b622-e75329d300b9",
    "jobTypeId": "convert-fasta-reference",
    "id": 139,
    "comment": "Import/Convert Fasta File to DataSet ConvertImportFastaOptions(/pbi/dept/secondary/siv/references/ecoliK12_pbi_March2013/sequence/ecoliK12_pbi_March2013.fasta,ecoliK12_pbi_March2013,haploid,Ecoli)",
    "createdAt": "2015-11-23T13:20:02.706-08:00",
    "jsonSettings": "{\"path\":\"/pbi/dept/secondary/siv/references/ecoliK12_pbi_March2013/sequence/ecoliK12_pbi_March2013.fasta\",\"name\":\"ecoliK12_pbi_March2013\",\"ploidy\":\"haploid\",\"organism\":\"Ecoli\"}"
  },
  {
    "name": "Job convert-fasta-reference",
    "updatedAt": "2015-11-23T13:20:52.834-08:00",
    "path": "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000140",
    "state": "FAILED",
    "uuid": "e0e36d53-32de-48e8-8c5c-c246db842d93",
    "jobTypeId": "convert-fasta-reference",
    "id": 140,
    "comment": "Import/Convert Fasta File to DataSet ConvertImportFastaOptions(/pbi/dept/secondary/siv/references/Rhodobacter_palustris_CGA0009/sequence/Rhodobacter_palustris_CGA0009.fasta,Rhodobacter_palustris_CGA0009,haploid,Rhodobacter_palustris)",
    "createdAt": "2015-11-23T13:20:52.834-08:00",
    "jsonSettings": "{\"path\":\"/pbi/dept/secondary/siv/references/Rhodobacter_palustris_CGA0009/sequence/Rhodobacter_palustris_CGA0009.fasta\",\"name\":\"Rhodobacter_palustris_CGA0009\",\"ploidy\":\"haploid\",\"organism\":\"Rhodobacter_palustris\"}"
  }
]

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/post/create_import-dataset_job_response_sample.json
{
  "name": "Job import-dataset",
  "updatedAt": "2016-02-23T11:54:26.429-08:00",
  "path": "",
  "state": "CREATED",
  "uuid": "18671448-ff4e-4ed9-a740-1bf8a8f4fcd1",
  "jobTypeId": "import-dataset",
  "id": 135,
  "comment": "Importing DataSet ImportDataSetOptions(/pbi/collections/315/3150104/r54007_20160221_004312/1_A01/m54007_160221_004320.subreadset.xml,PacBio.DataSet.SubreadSet)",
  "createdAt": "2016-02-23T11:54:26.429-08:00",
  "jsonSettings": "{\"path\":\"/pbi/collections/315/3150104/r54007_20160221_004312/1_A01/m54007_160221_004320.subreadset.xml\",\"datasetType\":\"PacBio.DataSet.SubreadSet\"}"
}
