=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/dataset_service_endpoints/dataset_types_list_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "pacbio.secondary.schemas.datasets.types.list",
  "version": "0.1.0",
  "title": "Dataset Types List",
  "description": "Array of objects describing Dataset Types",
  "type": "array",
  "minItems": 1,
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "title": "Dataset Type Display Name",
        "description": "Display name of this dataset type",
        "type": "string"
      },
      "updatedAt": {
        "title": "Updated at",
        "description": "Time when this dataset type was updated",
        "type": "string",
        "format": "date-time"
      },
      "description": {
        "title": "Dataset Type Description",
        "description": "Description of this dataset type",
        "type": "string"
      },
      "id": {
        "title": "Dataset Type Id",
        "description": "Identifier of this dataset type",
        "type": "string"
      },
      "createdAt": {
        "title": "Created at",
        "description": "Time when this dataset type was created",
        "type": "string",
        "format": "date-time"
      },
      "shortName": {
        "title": "Dataset Type Short Name",
        "description": "Short name of this dataset type",
        "type": "string"
      }
    },
    "required": [
      "name",
      "updatedAt",
      "description",
      "id",
      "createdAt",
      "shortName"
    ]
  },
  "additionalItems": false
}

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/dataset_service_endpoints/list_all_dataset_types_response_sample.json
[
  {
    "name": "Display name for PacBio.DataSet.HdfSubreadSet",
    "updatedAt": "2015-11-12T23:37:21.411",
    "description": "Description for PacBio.DataSet.HdfSubreadSet",
    "id": "PacBio.DataSet.HdfSubreadSet",
    "createdAt": "2015-11-12T23:37:21.411",
    "shortName": "hdfsubreads"
  },
  {
    "name": "Display name for PacBio.DataSet.ConsensusAlignmentSet",
    "updatedAt": "2015-11-12T23:37:21.411",
    "description": "Description for PacBio.DataSet.ConsensusAlignmentSet",
    "id": "PacBio.DataSet.ConsensusAlignmentSet",
    "createdAt": "2015-11-12T23:37:21.411",
    "shortName": "ccsalignments"
  },
  {
    "name": "Display name for PacBio.DataSet.ConsensusReadSet",
    "updatedAt": "2015-11-12T23:37:21.411",
    "description": "Description for PacBio.DataSet.ConsensusReadSet",
    "id": "PacBio.DataSet.ConsensusReadSet",
    "createdAt": "2015-11-12T23:37:21.411",
    "shortName": "ccsreads"
  },
  {
    "name": "Display name for PacBio.DataSet.ReferenceSet",
    "updatedAt": "2015-11-12T23:37:21.411",
    "description": "Description for PacBio.DataSet.ReferenceSet",
    "id": "PacBio.DataSet.ReferenceSet",
    "createdAt": "2015-11-12T23:37:21.411",
    "shortName": "references"
  },
  {
    "name": "Display name for PacBio.DataSet.SubreadSet",
    "updatedAt": "2015-11-12T23:37:21.411",
    "description": "Description for PacBio.DataSet.SubreadSet",
    "id": "PacBio.DataSet.SubreadSet",
    "createdAt": "2015-11-12T23:37:21.411",
    "shortName": "subreads"
  },
  {
    "name": "Display name for PacBio.DataSet.AlignmentSet",
    "updatedAt": "2015-11-12T23:37:21.411",
    "description": "Description for PacBio.DataSet.AlignmentSet",
    "id": "PacBio.DataSet.AlignmentSet",
    "createdAt": "2015-11-12T23:37:21.411",
    "shortName": "alignments"
  },
  {
    "name": "Display name for PacBio.DataSet.BarcodeSet",
    "updatedAt": "2015-11-12T23:37:21.411",
    "description": "Description for PacBio.DataSet.BarcodeSet",
    "id": "PacBio.DataSet.BarcodeSet",
    "createdAt": "2015-11-12T23:37:21.411",
    "shortName": "barcodes"
  },
  {
    "name": "Display name for PacBio.DataSet.ContigSet",
    "updatedAt": "2015-11-12T23:37:21.411",
    "description": "Description for PacBio.DataSet.ContigSet",
    "id": "PacBio.DataSet.ContigSet",
    "createdAt": "2015-11-12T23:37:21.410",
    "shortName": "contigs"
  }
]
