=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/job_events_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "pacbio.secondary.schemas.job.events",
	"version": "0.1.0",
	"title": "Job Events",
	"description": "Array of job events",
	"type": "array",
	"minItems": 1,
	"items": {
		"type" : "object",
		"properties": {
			"state": {
				"title": "Job State",
				"description": "Current job state, one of CREATED, SUBMITTED, RUNNING, SUCCESSFUL, FAILED, KILLED, STOPPED states",
				"type": "string"
			},
			"eventId": {
				"title": "Event Id",
				"description": "UUID of the event",
				"type": "string",
				"format": "uuid",
				"pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
			},
			"jobId": {
				"title": "Job Id",
				"description": "Identifier of the job that the event belongs to",
				"type": "integer"
			},
			"createdAt": {
				"title": "Created at",
				"description": "Time when this event was created",
				"type": "string",
				"format" : "date-time"
			},
			"message": {
				"title": "Message",
				"description": "Message describing this event",
				"type": "string"
			}
		},
		"required" : [
			"state",
			"eventId",
			"jobId",
			"createdAt",
			"message"
		]
	},
	"additionalItems" : false
}

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/get_jobs_merge-datasets_252_events.json
[
  {
    "state": "CREATED",
    "eventId": "fe5eeae7-dbcd-4e93-a55c-1467b3a9b50d",
    "jobId": 252,
    "createdAt": "2015-11-30T15:06:10.531-08:00",
    "message": "Created job 252 type merge-datasets with 1576c753-478c-46c6-ad44-9936665df1b7"
  },
  {
    "state": "SUBMITTED",
    "eventId": "362b2722-456c-4781-a953-a4c5e8d5eca2",
    "jobId": 252,
    "createdAt": "2015-11-30T15:06:12.010-08:00",
    "message": "Updating job id 1576c753-478c-46c6-ad44-9936665df1b7 to SUBMITTED"
  },
  {
    "state": "RUNNING",
    "eventId": "b4d94bf5-bd00-4778-9e89-1d73cf9d9336",
    "jobId": 252,
    "createdAt": "2015-11-30T15:06:12.171-08:00",
    "message": "Updating job id 1576c753-478c-46c6-ad44-9936665df1b7 to RUNNING"
  },
  {
    "state": "RUNNING",
    "eventId": "5516a6b9-3d72-4d04-bd14-108e71ab217e",
    "jobId": 252,
    "createdAt": "2015-11-30T15:06:12.232-08:00",
    "message": "Updating job id 1576c753-478c-46c6-ad44-9936665df1b7 to RUNNING"
  },
  {
    "state": "SUCCESSFUL",
    "eventId": "7d2b03ab-2aa8-4488-aeee-e3a2b4540485",
    "jobId": 252,
    "createdAt": "2015-11-30T15:06:12.556-08:00",
    "message": "Updating job id 1576c753-478c-46c6-ad44-9936665df1b7 to SUCCESSFUL"
  }
]

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/get_jobs_convert-fasta-reference_4_events.json
[
  {
    "state": "CREATED",
    "eventId": "d4ab8b0b-25c1-4e76-ae5d-2669afaf9ac2",
    "jobId": 4,
    "createdAt": "2015-11-13T11:57:37.665-08:00",
    "message": "Created job 4 type convert-fasta-reference with d0a65373-ac76-44c6-afbe-614bc15c6d0e"
  },
  {
    "state": "SUBMITTED",
    "eventId": "9f040d25-2876-45dd-9438-44fe49ef1361",
    "jobId": 4,
    "createdAt": "2015-11-13T11:57:39.107-08:00",
    "message": "Updating job id d0a65373-ac76-44c6-afbe-614bc15c6d0e to SUBMITTED"
  },
  {
    "state": "RUNNING",
    "eventId": "8c6ef1c7-055e-464d-84fc-e74db65fa518",
    "jobId": 4,
    "createdAt": "2015-11-13T11:57:39.184-08:00",
    "message": "Updating job id d0a65373-ac76-44c6-afbe-614bc15c6d0e to RUNNING"
  },
  {
    "state": "RUNNING",
    "eventId": "6694db93-4092-41c4-97fb-da680753a86b",
    "jobId": 4,
    "createdAt": "2015-11-13T11:57:39.275-08:00",
    "message": "Updating job id d0a65373-ac76-44c6-afbe-614bc15c6d0e to RUNNING"
  },
  {
    "state": "SUCCESSFUL",
    "eventId": "6ebb1934-b4cd-407f-af68-92be513a3d39",
    "jobId": 4,
    "createdAt": "2015-11-13T11:57:40.654-08:00",
    "message": "Updating job id d0a65373-ac76-44c6-afbe-614bc15c6d0e to SUCCESSFUL"
  }
]
