=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/job_datastore_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "pacbio.secondary.schemas.job.datastore",
  "version": "0.1.0",
  "title": "Job Datastore",
  "description": "Array of job datastore files",
  "type": "array",
  "minItems": 1,
  "items": {
    "type": "object",
    "properties": {
      "fileTypeId": {
        "title": "File Type Id",
        "description": "File type identifier, e.g. PacBio.FileTypes.JsonReport",
        "type": "string"
      },
      "sourceId": {
        "title": "Source Id",
        "description": "Source identifier of this datastore, e.g. pbscala::import_dataset",
        "type": "string"
      },
      "uuid": {
        "title": "UUID",
        "description": "UUID of the datastore file",
        "type": "string",
        "format": "uuid",
        "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
      },
      "jobId": {
        "title": "Job Id",
        "description": "Identifier of the job that emitted this datastore file",
        "type": "integer"
      },
      "jobUUID": {
        "title": "Job UUID",
        "description": "UUID of the job that emitted this datastore file",
        "type": "string",
        "format": "uuid",
        "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
      },
      "createdAt": {
        "title": "Created at",
        "description": "Time when this datastore file was created",
        "type": "string",
        "format": "date-time"
      },
      "importedAt": {
        "title": "Imported at",
        "description": "Time when this datastore file was imported",
        "type": "string",
        "format": "date-time"
      },
      "modifiedAt": {
        "title": "Modified at",
        "description": "Time when this datastore file was modified",
        "type": "string",
        "format": "date-time"
      },
      "path": {
        "title": "Datastore File Path",
        "description": "Path to the datastore file",
        "type": "string",
        "format": "uri"
      },
      "fileSize": {
        "title": "Datastore File Size",
        "description": "Size of the datastore file",
        "type": "integer"
      }
    },
    "required": [
      "fileTypeId",
      "sourceId",
      "uuid",
      "jobId",
      "jobUUID",
      "createdAt",
      "importedAt",
      "modifiedAt",
      "path",
      "fileSize"
    ]
  },
  "additionalItems": false
}

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/get_jobs_merge-datasets_252_datastore.json
[{
		"modifiedAt" : "2015-11-30T15:06:12.287",
		"fileTypeId" : "PacBio.DataSet.SubreadSet",
		"path" : "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000252/merged.dataset.xml",
		"uuid" : "7aaf577a-9416-413f-9948-7c8d3dfa2a8d",
		"fileSize" : 13240,
		"importedAt" : "2015-11-30T15:06:12.287",
		"jobId" : 252,
		"createdAt" : "2015-11-30T15:06:12.287",
		"jobUUID" : "1576c753-478c-46c6-ad44-9936665df1b7",
		"sourceId" : "pbscala::merge_dataset"
	}
]

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/get_jobs_import-dataset_17_datastore.json
[{
		"modifiedAt" : "2015-11-16T21:42:05.882",
		"fileTypeId" : "PacBio.DataSet.SubreadSet",
		"path" : "/pbi/collections/313/3130023/r54012_20151116_234924/2_B01/m54012_151117_023631.subreadset.xml",
		"uuid" : "9d372452-b24b-41a9-9a3d-3ab9d477b953",
		"fileSize" : 9592,
		"importedAt" : "2015-11-16T21:42:05.882",
		"jobId" : 17,
		"createdAt" : "2015-11-16T21:42:05.882",
		"jobUUID" : "14bac755-2357-4ade-b26a-eb6af41e7c77",
		"sourceId" : "pbscala::import_dataset"
	}, {
		"modifiedAt" : "2015-11-16T21:42:06.023",
		"fileTypeId" : "PacBio.FileTypes.JsonReport",
		"path" : "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000017/import-datastore-report.json",
		"uuid" : "1ab22884-c789-4767-b269-3055c2b68e29",
		"fileSize" : 1634,
		"importedAt" : "2015-11-16T21:42:06.023",
		"jobId" : 17,
		"createdAt" : "2015-11-16T21:42:06.023",
		"jobUUID" : "14bac755-2357-4ade-b26a-eb6af41e7c77",
		"sourceId" : "pbscala::import_dataset"
	}
]

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/get_jobs_pbsmrtpipe_38_datastore.json
[{
		"modifiedAt" : "2015-11-18T12:58:47.944",
		"fileTypeId" : "PacBio.DataSet.AlignmentSet",
		"path" : "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000038/tasks/pbsmrtpipe.tasks.gather_alignmentset-1/file.alignmentset.xml",
		"uuid" : "a8284a60-5b17-1744-6c31-44264dffdbb0",
		"fileSize" : 89832,
		"importedAt" : "2015-11-18T12:58:47.944",
		"jobId" : 38,
		"createdAt" : "2015-11-18T12:58:47.944",
		"jobUUID" : "ea3c0962-f37b-43b6-82b3-051d41dc82c0",
		"sourceId" : "pbsmrtpipe.tasks.gather_alignmentset-PacBio.DataSet.AlignmentSet"
	}, {
		"modifiedAt" : "2015-11-18T13:00:21.104",
		"fileTypeId" : "PacBio.FileTypes.JsonReport",
		"path" : "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000038/tasks/pbreports.tasks.mapping_stats-0/mapping_stats_report.json",
		"uuid" : "63e31de0-d295-41e6-bf1a-8d3beda06892",
		"fileSize" : 6326,
		"importedAt" : "2015-11-18T13:00:21.104",
		"jobId" : 38,
		"createdAt" : "2015-11-18T13:00:21.104",
		"jobUUID" : "ea3c0962-f37b-43b6-82b3-051d41dc82c0",
		"sourceId" : "pbreports.tasks.mapping_stats-PacBio.FileTypes.JsonReport"
	}, {
		"modifiedAt" : "2015-11-18T13:00:43.196",
		"fileTypeId" : "PacBio.FileTypes.gff",
		"path" : "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000038/tasks/pbsmrtpipe.tasks.gather_gff-1/file.gff",
		"uuid" : "0e89ecf9-416f-439d-bfe4-78e539b41454",
		"fileSize" : 21783,
		"importedAt" : "2015-11-18T13:00:43.196",
		"jobId" : 38,
		"createdAt" : "2015-11-18T13:00:43.196",
		"jobUUID" : "ea3c0962-f37b-43b6-82b3-051d41dc82c0",
		"sourceId" : "pbsmrtpipe.tasks.gather_gff-PacBio.FileTypes.gff"
	}, {
		"modifiedAt" : "2015-11-18T13:00:51.943",
		"fileTypeId" : "PacBio.DataSet.ContigSet",
		"path" : "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000038/tasks/pbsmrtpipe.tasks.gather_contigset-1/file.contigset.xml",
		"uuid" : "2d0c7852-0050-6bd3-d6af-0d8020112f54",
		"fileSize" : 11886,
		"importedAt" : "2015-11-18T13:00:51.943",
		"jobId" : 38,
		"createdAt" : "2015-11-18T13:00:51.943",
		"jobUUID" : "ea3c0962-f37b-43b6-82b3-051d41dc82c0",
		"sourceId" : "pbsmrtpipe.tasks.gather_contigset-PacBio.DataSet.ContigSet"
	}, {
		"modifiedAt" : "2015-11-18T13:00:56.217",
		"fileTypeId" : "PacBio.FileTypes.Fastq",
		"path" : "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000038/tasks/pbsmrtpipe.tasks.gather_fastq-1/file.fastq",
		"uuid" : "9d310ee2-e15b-4683-80af-2c7af2415075",
		"fileSize" : 99068,
		"importedAt" : "2015-11-18T13:00:56.217",
		"jobId" : 38,
		"createdAt" : "2015-11-18T13:00:56.217",
		"jobUUID" : "ea3c0962-f37b-43b6-82b3-051d41dc82c0",
		"sourceId" : "pbsmrtpipe.tasks.gather_fastq-PacBio.FileTypes.Fastq"
	}, {
		"modifiedAt" : "2015-11-18T13:01:05.093",
		"fileTypeId" : "PacBio.FileTypes.log",
		"path" : "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000038/logs/master.log",
		"uuid" : "3ba3fad4-613f-477e-b397-8464d5c366a3",
		"fileSize" : 634,
		"importedAt" : "2015-11-18T13:01:05.093",
		"jobId" : 38,
		"createdAt" : "2015-11-18T13:01:05.093",
		"jobUUID" : "ea3c0962-f37b-43b6-82b3-051d41dc82c0",
		"sourceId" : "pbsmrtpipe::master.log"
	}, {
		"modifiedAt" : "2015-11-18T13:01:05.287",
		"fileTypeId" : "PacBio.FileTypes.log",
		"path" : "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000038/logs/pbsmrtpipe.log",
		"uuid" : "9c183df8-f7eb-475f-a0f7-e3697370b1dd",
		"fileSize" : 0,
		"importedAt" : "2015-11-18T13:01:05.287",
		"jobId" : 38,
		"createdAt" : "2015-11-18T13:01:05.287",
		"jobUUID" : "ea3c0962-f37b-43b6-82b3-051d41dc82c0",
		"sourceId" : "pbsmrtpipe::pbsmrtpipe.log"
	}
]

=== Global19-atlassian-net/smrtflow/docs/SMRT_Secondary_Service_API/jobs_service_endpoints/get_jobs_convert-fasta-reference_4_datastore.json
[{
		"modifiedAt" : "2015-11-13T11:57:39.331",
		"fileTypeId" : "PacBio.DataSet.ReferenceSet",
		"path" : "/pbi/dept/secondary/siv/smrtlink/smrtlink-beta/smrtsuite_166987/userdata/jobs_root/000/000004/pacbio-reference/lambdaNEB/referenceset.xml",
		"uuid" : "e5433224-d185-4e73-af45-ee7c8154a768",
		"fileSize" : 2427,
		"importedAt" : "2015-11-13T11:57:39.331",
		"jobId" : 4,
		"createdAt" : "2015-11-13T11:57:39.331",
		"jobUUID" : "d0a65373-ac76-44c6-afbe-614bc15c6d0e",
		"sourceId" : "pbscala::convert_fasta_to_dataset"
	}
]
